[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[accesslog]
  filePath = "/var/log/access.log"
[log]
  level="INFO"
  filePath = "/var/log/traefik.log"

[api]
  dashboard=true
  debug=true

[providers.docker]
  watch = true
  exposedByDefault = false
  network = "proxy"

[entryPoints]
  [entryPoints.web]
    address=":80"
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"

  [entryPoints.websecure]
    address=":443"

[certificatesResolvers]
  [certificatesResolvers.letsresolve]
    [certificatesResolvers.letsresolve.acme]
      email = "bastienprudor@gmail.com"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      storage = "acme.json"
      keyType = "EC384"
      [certificatesResolvers.letsresolve.acme.httpChallenge]
        entryPoint = "web"
