// <auto-generated />
using System;
using MaViCS.Domain.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaViCS.Domain.Persistance.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221024180546_InitialMig")]
    partial class InitialMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MaViCS.Domain.Models.Show", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("TourId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TourId");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "Application",
                            CreatedOn = new DateTime(2022, 10, 24, 18, 5, 46, 316, DateTimeKind.Utc).AddTicks(5240),
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1L,
                            TourId = 1L
                        });
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Talent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("HomeTownId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeTownId");

                    b.ToTable("Talents");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "Application",
                            CreatedOn = new DateTime(2022, 10, 24, 18, 5, 46, 316, DateTimeKind.Utc).AddTicks(5208),
                            HomeTownId = 1L,
                            Name = "Gura",
                            Surname = "Gawr",
                            Title = "Shark-Girl Idol"
                        });
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Tour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("TalentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TalentId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "Application",
                            CreatedOn = new DateTime(2022, 10, 24, 18, 5, 46, 316, DateTimeKind.Utc).AddTicks(5225),
                            Name = "Shark First Concert",
                            StartedOn = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TalentId = 1L
                        });
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Town", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedBy = "Application",
                            CreatedOn = new DateTime(2022, 10, 24, 18, 5, 46, 316, DateTimeKind.Utc).AddTicks(5077),
                            Description = "A Sunken city",
                            Latitude = 0m,
                            Longitude = 0m,
                            Name = "Atlantis",
                            Region = "Ocean"
                        });
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Show", b =>
                {
                    b.HasOne("MaViCS.Domain.Models.Town", "Location")
                        .WithMany("Shows")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MaViCS.Domain.Models.Tour", "Tour")
                        .WithMany("Shows")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Talent", b =>
                {
                    b.HasOne("MaViCS.Domain.Models.Town", "HomeTown")
                        .WithMany("Talents")
                        .HasForeignKey("HomeTownId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomeTown");
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Tour", b =>
                {
                    b.HasOne("MaViCS.Domain.Models.Talent", "Talent")
                        .WithMany("Tours")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Talent", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Tour", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("MaViCS.Domain.Models.Town", b =>
                {
                    b.Navigation("Shows");

                    b.Navigation("Talents");
                });
#pragma warning restore 612, 618
        }
    }
}
